spring.application.name=javafx

api.base-url=http://localhost:8083
#api.base-url=http://cafe7788.cafe24.com

# INFO / DEBUG / WARN 대부분 제거
logging.level.com.swna.javafx=ERROR

# POS 전체 운영 로그 제한
logging.level.com.swna.javafx.application.pos=ERROR

# ViewModel도 같이 제한
logging.level.com.swna.javafx.application.pos.PosViewModel=ERROR

# Scanner 엔진도 제한
logging.level.com.swna.javafx.infrastructure.scanner=ERROR