spring.application.name=javafx
spring.http.codecs.max-in-memory-size=10MB

api.base-url=http://localhost:8083
#api.base-url=http://cafe7788.cafe24.com

# INFO / DEBUG / WARN / ERROR 대부분 제거
logging.level.com.swna.javafx=INFO

# POS 전체 운영 로그 제한
logging.level.com.swna.javafx.application.pos=DEBUG

# ViewModel도 같이 제한
logging.level.com.swna.javafx.application.pos.PosViewModel=INFO

# Scanner 엔진도 제한
logging.level.com.swna.javafx.infrastructure.scanner=DEBUG

# ========================================
# 프린터 설정 - 운영 환경
# ========================================

# Console 출력 비활성화
print.debug.console=true

# 실제 프린터 출력 활성화
print.debug.real=true